name: Build and Deploy

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup SourcePawn compiler 1.12
      uses: rumblefrog/setup-sp@master
      with:
        version: '1.12.7163'

    - name: Create external dependency directories
      run: |
        mkdir includes
        mkdir includes/multicolors

    - name: Copy local include files to dependency directory
      run: cp -r scripting/include/* includes/

    - name: Fetch small dependencies
      run: |
        wget https://raw.githubusercontent.com/Impact123/AutoExecConfig/development/autoexecconfig.inc -P includes
        wget https://raw.githubusercontent.com/VoiDeD/sourcemod-botcontroller/master/scripting/botcontroller.inc -P includes
        wget https://raw.githubusercontent.com/geominorai/sm-octree/master/scripting/include/octree.inc -P includes
        wget https://raw.githubusercontent.com/Bara/Multi-Colors/master/addons/sourcemod/scripting/include/multicolors.inc -P includes
        wget https://raw.githubusercontent.com/Bara/Multi-Colors/master/addons/sourcemod/scripting/include/multicolors/colors.inc -P includes/multicolors
        wget https://raw.githubusercontent.com/Bara/Multi-Colors/master/addons/sourcemod/scripting/include/multicolors/morecolors.inc  -P includes/multicolors
        wget https://raw.githubusercontent.com/asherkin/TF2Items/master/pawn/tf2items.inc -P includes

    - name: Fetch smlib dependency
      uses: actions/checkout@v4
      with:
        repository: bcserv/smlib
        ref: transitional_syntax
        path: smlib

    - name: Copy smlib to dependency directory
      run: cp -r smlib/scripting/include/* includes

    - name: Move dependency directory into scripting
      run: mv includes scripting

    - name: Create plugins folders
      run: |
        mkdir plugins
        mkdir -p plugins/smbl/action/common/attack
        mkdir plugins/smbl/action/soldier
        mkdir plugins/smbl/action/utility
        mkdir -p plugins/smbl/controller/all
        mkdir plugins/smbl/controller/soldier
        mkdir plugins/smbl/director
        mkdir plugins/smbl/gamemode
        mkdir plugins/smbl/monitor
        mkdir plugins/smbl/navigation
        mkdir plugins/smbl/observable
        mkdir plugins/smbl/process

    - name: Build plugins
      working-directory: ./scripting
      run: |
        spcomp -iincludes smbl.sp                                                         -o ../plugins/smbl.smx
        spcomp -iincludes smbl/action/common/smbl_action_common_idle.sp                   -o ../plugins/smbl/action/common/smbl_action_common_idle.smx
        spcomp -iincludes smbl/action/common/smbl_action_common_move.sp                   -o ../plugins/smbl/action/common/smbl_action_common_move.smx
        spcomp -iincludes smbl/action/common/attack/smbl_action_common_attack_shoot.sp    -o ../plugins/smbl/action/common/attack/smbl_action_common_attack_shoot.smx
        spcomp -iincludes smbl/action/soldier/smbl_action_soldier_attack.sp               -o ../plugins/smbl/action/soldier/smbl_action_soldier_attack.smx
        spcomp -iincludes smbl/action/soldier/smbl_action_soldier_move.sp                 -o ../plugins/smbl/action/soldier/smbl_action_soldier_move.smx
        spcomp -iincludes smbl/action/soldier/smbl_action_soldier_rocketjump.sp           -o ../plugins/smbl/action/soldier/smbl_action_soldier_rocketjump.smx
        spcomp -iincludes smbl/action/utility/smbl_action_utility.sp                      -o ../plugins/smbl/action/utility/smbl_action_utility.smx
        spcomp -iincludes smbl/controller/all/smbl_controller_all_generic.sp              -o ../plugins/smbl/controller/all/smbl_controller_all_generic.smx
        spcomp -iincludes smbl/controller/soldier/smbl_controller_soldier_trolldier.sp    -o ../plugins/smbl/controller/soldier/smbl_controller_soldier_trolldier.smx
        spcomp -iincludes smbl/director/smbl_director_debug.sp                            -o ../plugins/smbl/director/smbl_director_debug.smx
        spcomp -iincludes smbl/gamemode/smbl_gamemode_mga.sp                              -o ../plugins/smbl/gamemode/smbl_gamemode_mga.smx
        spcomp -iincludes smbl/monitor/smbl_monitor_targetacquisition_fov.sp              -o ../plugins/smbl/monitor/smbl_monitor_targetacquisition_fov.smx
        spcomp -iincludes smbl/navigation/smbl_nav_mesh.sp                                -o ../plugins/smbl/navigation/smbl_nav_mesh.smx
        spcomp -iincludes smbl/navigation/smbl_nav_mesh_editor.sp                         -o ../plugins/smbl/navigation/smbl_nav_mesh_editor.smx
        spcomp -iincludes smbl/observable/smbl_observable_player_events.sp                -o ../plugins/smbl/observable/smbl_observable_player_events.smx
        spcomp -iincludes smbl/process/smbl_process_combat.sp                             -o ../plugins/smbl/process/smbl_process_combat.smx
        spcomp -iincludes smbl/process/smbl_process_idle.sp                               -o ../plugins/smbl/process/smbl_process_idle.smx
        spcomp -iincludes smbl/process/smbl_process_investigate.sp                        -o ../plugins/smbl/process/smbl_process_investigate.smx
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
          name: smbl-plugins
          path: plugins/

    - name: Remove external dependency directory
      run: rm -r scripting/includes

    - name: Prepare release bundles
      if: github.ref == 'refs/heads/master'
      run: |
        zip -r smbl-bundle.zip LICENSE plugins scripting
        tar -czf smbl-bundle.tar.gz LICENSE plugins scripting

    - name: "Release development build"
      if: github.ref == 'refs/heads/master'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          smbl-bundle.zip
          smbl-bundle.tar.gz
